name: Build Android APKs (SOMA App Q.B)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build Buyer APK
        run: flutter build apk --release -t lib/buyer_main.dart -o build/app/outputs/flutter-apk/buyer.apk

      - name: Build Seller APK
        run: flutter build apk --release -t lib/seller_main.dart -o build/app/outputs/flutter-apk/seller.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: |
            build/app/outputs/flutter-apk/buyer.apk
            build/app/outputs/flutter-apk/seller.apk
