name: Build Android APKs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter 3.19.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      # پاک‌سازی کش‌های خراب Gradle / Wrapper
      - name: Clean Gradle caches
        run: |
          rm -rf ~/.gradle/wrapper
          rm -rf ~/.gradle/caches
          rm -rf android/.gradle

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get

      - name: Build Buyer APK
        run: flutter build apk --release -t lib/buyer_main.dart

      - name: Save Buyer APK
        run: |
          mkdir -p apks
          cp build/app/outputs/flutter-apk/app-release.apk apks/buyer.apk

      - name: Build Seller APK
        run: flutter build apk --release -t lib/seller_main.dart

      - name: Save Seller APK
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk apks/seller.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: apks/
          if-no-files-found: error
