name: Build Android APKs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}   # برای دکمه Run workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter 3.19.6
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Flutter doctor
        run: flutter --version

      - name: Flutter clean & pub get
        run: |
          flutter clean
          flutter pub get

      # چون gradlew / jar داخل ریپو نیست، Wrapper را داخل Runner می‌سازیم
      - name: Bootstrap Gradle Wrapper (7.6.3)
        working-directory: android
        run: |
          curl -sL https://services.gradle.org/distributions/gradle-7.6.3-bin.zip -o gradle.zip
          unzip -q gradle.zip
          ./gradle-7.6.3/bin/gradle wrapper --gradle-version 7.6.3
          rm -rf gradle.zip gradle-7.6.3

      # بیلد Buyer
      - name: Build Buyer APK
        run: flutter build apk --release -t lib/buyer_main.dart

      - name: Save Buyer APK
        run: |
          mkdir -p apks
          cp build/app/outputs/flutter-apk/app-release.apk apks/buyer.apk

      # بیلد Seller
      - name: Build Seller APK
        run: flutter build apk --release -t lib/seller_main.dart

      - name: Save Seller APK
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk apks/seller.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: soma-apks
          path: apks/
          retention-days: 14
